### ISSUE TITLE
YKF リニューアル対応

### ISSUE THREAD

**Issue by ikemura23** [ikemura23/Yaimafuni-Backend#43]
エラーログ

```
Debugger attached.

> scraping-yaimafuni@1.0.0 start
> node src/index.js

Debugger attached.
main init
main start
  updateAnneiList start
    getAnneiUpdateTimeAndComment start
    getAnneiList start
    saveAnneiList start
      update complete!
    updateAnneiList end
  updateAnneiDetail start
    getAnneiDetail start
      getAnneiDetail end
    saveAnneiDetail start
      update complete!
    saveAnneiDetail end
  updateAnneiDetail end
開始: ykf 一覧
{}
update complete!
終了: ykf 一覧
開始:ykf 時間+アナウンス
Error: Error: failed to find element matching selector "#operationstatus > div > div.statusdate"
    at ElementHandle.$eval (/Users/k_ikemura/dev/Yaimafuni-Backend/node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:658:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getData (/Users/k_ikemura/dev/Yaimafuni-Backend/src/list/ykf/ykf_time_and_announce.js:83:12)
    at async getUpdateTime (/Users/k_ikemura/dev/Yaimafuni-Backend/src/list/ykf/ykf_time_and_announce.js:53:18)
    at async module.exports (/Users/k_ikemura/dev/Yaimafuni-Backend/src/list/ykf/ykf_time_and_announce.js:22:28)
    at async /Users/k_ikemura/dev/Yaimafuni-Backend/src/index.js:31:5 異常: YKF 時間+アナウンスでエラー
Post to Slack: 異常: YKF 時間+アナウンスのスクレイピングでエラー発生! Error: Error: failed to find element matching selector "#operationstatus > div > div.statusdate"
    at ElementHandle.$eval (/Users/k_ikemura/dev/Yaimafuni-Backend/node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:658:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getData (/Users/k_ikemura/dev/Yaimafuni-Backend/src/list/ykf/ykf_time_and_announce.js:83:12)
    at async getUpdateTime (/Users/k_ikemura/dev/Yaimafuni-Backend/src/list/ykf/ykf_time_and_announce.js:53:18)
    at async module.exports (/Users/k_ikemura/dev/Yaimafuni-Backend/src/list/ykf/ykf_time_and_announce.js:22:28)
    at async /Users/k_ikemura/dev/Yaimafuni-Backend/src/index.js:31:5
終了:ykf 時間+アナウンス
開始: ykf 詳細
devLocalNodes is empty
ReferenceError: tableName is not defined
    at module.exports (/Users/k_ikemura/dev/Yaimafuni-Backend/src/detail/ykf/detail_ykf.js:30:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/k_ikemura/dev/Yaimafuni-Backend/src/index.js:32:5 ykf一覧でエラー
Post to Slack: ykf一覧のスクレイピングでエラー発生! ReferenceError: tableName is not defined
    at module.exports (/Users/k_ikemura/dev/Yaimafuni-Backend/src/detail/ykf/detail_ykf.js:30:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/k_ikemura/dev/Yaimafuni-Backend/src/index.js:32:5
終了: ykf 詳細
開始 : 台風 tenkijp
完了 : 台風 tenkijp
yahoo start

          8月21日(日)

        
{
  date: '8月21日(日)',
  weather: '晴時々曇',
  temperature: { hight: '34℃[0]', low: '28℃[-1]' },
  wave: '1メートル',
  wind: '南西の風日中北西の風'
}
yahoo end
開始 港別の作成 
Waiting for the debugger to disconnect...
/Users/k_ikemura/dev/Yaimafuni-Backend/src/top/top_port.js:50
        ykf: ykf.taketomi
                 ^

TypeError: Cannot read properties of null (reading 'taketomi')
    at createSendData (/Users/k_ikemura/dev/Yaimafuni-Backend/src/top/top_port.js:50:18)
    at module.exports (/Users/k_ikemura/dev/Yaimafuni-Backend/src/top/top_port.js:14:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/k_ikemura/dev/Yaimafuni-Backend/src/index.js:35:5
```

**Comment by ikemura23** [comment]
またホームページがリニューアルされてた。。。

リニューアル告知
https://www.yaeyama.co.jp/news/detail.php?id=1

運行情報
https://www.yaeyama.co.jp/operation.html

**Comment by ikemura23** [comment]
直したのでクローズ
